name: "wd_tagger"
backend: "onnxruntime"
max_batch_size: 8
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [448, 448, 3]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [10861]
  }
]
dynamic_batching {
  preferred_batch_size: [1, 4, 8]
  max_queue_delay_microseconds: 100
}
instance_group [
  {
    kind: KIND_GPU
    gpus: [0]
    count: 1
  }
]
