name: "fashion_clip"
backend: "onnxruntime"
max_batch_size: 16
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [3, 224, 224]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [512]
  }
]
dynamic_batching {
  preferred_batch_size: [1, 4, 8, 16]
  max_queue_delay_microseconds: 100
}
instance_group [
  {
    kind: KIND_GPU
    gpus: [0]
    count: 1
  }
]
